development:
  clients:
    default:
      database: bbn_weixin_reply_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: bbn_weixin_reply_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1